# File: .github/workflows/manual-ftp-publish.yml
name: Manual FTP Publish public_html

on:
  workflow_dispatch:

jobs:
  
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWORD }}
        local-dir: ${{ secrets.LOCAL_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
